In [23]:
import torch
import numpy as np
t = torch.tensor([[1, 10, 200],[2,3,4]])
mask = np.array([[1, 1, -np.infty],[1, -np.infty, -np.infty]])
masked_t = t * mask
print(t)
print(masked_t)
max_Q = torch.max(masked_t, 1)[0]
print(max_Q)

tensor([[  1,  10, 200],
        [  2,   3,   4]])
tensor([[ 1., 10., -inf],
        [ 2., -inf, -inf]], dtype=torch.float64)
tensor([10.,  2.], dtype=torch.float64)


In [ ]:
data # 6
mask # 5 true, false
data_valid = data[mask]
data_unvalid = data[~mask]

tansitions_valid = Transitions[mask]
tansitions_unvalid = Transitions[~mask]

action_valid = transitions_valid.actterion




In [8]:
import numpy as np
table = np.zeros((3, 3, 3))
feature = np.array([1, 2])
q_values = table[feature]
print(q_values)

[0. 0. 0.]
