In [1]:
cd training_data

c:\Users\User\Documents\Studium\Machine Learning\Machine Learning Essentials\Submissions\Project\git\mle-ss23_final-project\training_data


In [2]:
cd 2023-08-19_16-16-06-636156

c:\Users\User\Documents\Studium\Machine Learning\Machine Learning Essentials\Submissions\Project\git\mle-ss23_final-project\training_data\2023-08-19_16-16-06-636156


In [3]:
ls

 Datentr�ger in Laufwerk C: ist Win10-Prof
 Volumeseriennummer: BADD-6E6D

 Verzeichnis von c:\Users\User\Documents\Studium\Machine Learning\Machine Learning Essentials\Submissions\Project\git\mle-ss23_final-project\training_data\2023-08-19_16-16-06-636156

19.08.2023  16:16    <DIR>          .
19.08.2023  16:16    <DIR>          ..
19.08.2023  16:16         1.479.960 round1.pkl
19.08.2023  16:16           806.600 round10.pkl
19.08.2023  16:16           939.779 round2.pkl
19.08.2023  16:16         1.258.129 round3.pkl
19.08.2023  16:16         1.465.222 round4.pkl
19.08.2023  16:16         1.472.372 round5.pkl
19.08.2023  16:16         1.388.630 round6.pkl
19.08.2023  16:16         1.079.995 round7.pkl
19.08.2023  16:16         1.468.988 round8.pkl
19.08.2023  16:16         1.093.479 round9.pkl
              10 Datei(en),     12.453.154 Bytes
               2 Verzeichnis(se), 147.673.223.168 Bytes frei


In [62]:
import pandas as pd
import numpy as np
file = 'round1.pkl'
data = pd.read_pickle(file)
print(data.columns)
data.head(10)

Index(['round', 'step', 'field', 'agents', 'bombs', 'coins', 'explosion_map'], dtype='object')


round  step                                              field  \
0      1     1  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
1      1     2  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
2      1     3  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
3      1     4  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
4      1     5  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
5      1     6  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
6      1     7  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
7      1     8  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
8      1     9  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   
9      1    10  [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...   

                                              agents  \
0  [(rule_based_agent_0, 0, True, (15, 1)), (rule...   
1  [(rule_based_agent_0, 0, True, (14, 1)), (rule...   
2  [(rule_based_agent_0, 0, False, (14, 1)), (rul...   
3  [(rule_based_agent_0, 0, False, (15, 1)), (rul...   
4  [(rule_based_agent_0, 0, False, (15, 2)), (rul...   
5  [(rule_based_agent_0, 0, False, (15, 3)), (rul...   
6  [(rule_based_agent_0, 0, False, (15, 2)), (rul...   
7  [(rule_based_agent_0, 0, False, (15, 3)), (rul...   
8  [(rule_based_agent_0, 0, True, (14, 3)), (rule...   
9  [(rule_based_agent_0, 0, False, (14, 3)), (rul...   

                                               bombs      coins  \
0                                                 []         []   
1                                                 []         []   
2  [((1, 14), 3), ((1, 2), 3), ((15, 14), 3), ((1...         []   
3  [((1, 14), 2), ((1, 2), 2), ((15, 14), 2), ((1...         []   
4  [((1, 14), 1), ((1, 2), 1), ((15, 14), 1), ((1...         []   
5  [((1, 14), 0), ((1, 2), 0), ((15, 14), 0), ((1...         []   
6                                                 []  [(13, 1)]   
7                                                 []  [(13, 1)]   
8                                                 []  [(13, 1)]   
9                                     [((14, 3), 3)]  [(13, 1)]   

                                       explosion_map  
0  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
1  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
2  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
3  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
4  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
5  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
6  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
7  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
8  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
9  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...

In [65]:
def get_blast_coords(x, y, field, power=3):
        blast_coords = [(x, y)]

        for i in range(1, power + 1):
            if field[x + i, y] == -1:
                break
            blast_coords.append((x + i, y))
        for i in range(1, power + 1):
            if field[x - i, y] == -1:
                break
            blast_coords.append((x - i, y))
        for i in range(1, power + 1):
            if field[x, y + i] == -1:
                break
            blast_coords.append((x, y + i))
        for i in range(1, power + 1):
            if field[x, y - i] == -1:
                break
            blast_coords.append((x, y - i))

        return blast_coords

[(15, 15), (14, 15), (13, 15), (12, 15), (15, 14), (15, 13), (15, 12)]

In [125]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder

field = data['field'][3].copy()
bombs = data['bombs'][3].copy()
print(bombs)

field[field==1] = 2
field[field==0] = 1

grid = Grid(matrix=field)
start = grid.node(1, 1)
end_bombs = [grid.node(bomb[0][0],bomb[0][1]) for bomb in bombs]


finder = AStarFinder()
for (end,bomb) in zip(end_bombs, bombs):
    path, runs = finder.find_path(start, end, grid)
    bomb_timer = bomb[1]
    print(len(path),bomb_timer+2)
    
    if len(path)<=bomb_timer+2:
        for pos in get_blast_coords(end.x, end.y,field):
            field [pos[0],pos[1]] =-1
    grid.cleanup()

#print(field.T[::-1])
grid = Grid(matrix=field)
start = grid.node(1, 1)
end = grid.node(12,3)

finder = AStarFinder()

path, runs = finder.find_path(start, end, grid)
print('operations:', runs, 'path length:', len(path))
print(grid.grid_str(path=path, start=start, end=end))

[((1, 14), 2), ((1, 2), 2), ((15, 14), 2), ((14, 1), 2)]
14 4
2 4
28 4
14 4
operations: 29 path length: 14
+-----------------+
|#################|
|#s####          #|
|#x# # # # # # # #|
|#xxxxxxxxxxxe   #|
|# # # # # # # # #|
|#               #|
|# # # # # # # # #|
|#               #|
|# # # # # # # # #|
|#               #|
|# # # # # # # # #|
|#               #|
|# # # # # # # # #|
|#               #|
|# # # # # # # # #|
|#               #|
|#################|
+-----------------+


In [26]:
for i, row in enumerate(data):
    i = 50
    agents = data.iloc[i]['agents']
    bombs = data.iloc[i]['bombs']
    coins = data.iloc[i]['coins']
    number_expl_map = np.count_nonzero(data.iloc[i]['explosion_map'])
    explosions = np.transpose(np.nonzero(data.iloc[i]['explosion_map']))
    
    for agent in agents:
        print(agent)
        pos_agent = agent[3]
        print(pos_agent)
        break
    break

0
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[]
('rule_based_agent_0', 1, False, (13, 9))
(13, 9)
