In [ ]:
data # 6
mask # 5 true, false
data_valid = data[mask]
data_unvalid = data[~mask]

tansitions_valid = Transitions[mask]
tansitions_unvalid = Transitions[~mask]

action_valid = transitions_valid.actterion




In [ ]:
import numpy as np
import torch
table = torch.zeros((3, 3, 3))
feature = torch.tensor([1, 2]) # old_state
q_values = table[*feature]
print(q_values)

In [ ]:
import torch
PATH = "model/my-model_stats.pt"
table = torch.load(PATH)
print(table.shape)
print(torch.sum(table > 0))

In [1]:
%cd "/home/gromovl/Programming/ml_final-project/mle-ss23_final-project"

/home/gromovl/Programming/ml_final-project/mle-ss23_final-project


In [5]:
import numpy as np
from helper import get_safety_feature, get_field_feature, get_blast_coords
field = np.full((17, 17), -1) # empty field

# Place walls in between
aisles = {} #store locations in a dictionary
for i in range(1,8):
   aisles[2*i-1] = [i for i in range(1,16)] #3,5,7,9,11,13,15
   aisles[2*i] = [1,3,5,7,9,11,13,15] #2,4,6,8,10,12,14,16

aisles[15] = [i for i in range(1,16)]


# Set all walls
for row_index in range(1,16):
  for column_index in aisles[row_index]:
    field[row_index, column_index] = 0

#print(np.sum(field == 0))


agent_pos = (7, 9)

explosion_map = np.zeros((17, 17))

bombs = [((agent_pos[0] + 1, agent_pos[1]), 3), 
         #((agent_pos[0], agent_pos[1] - 2), 1)
        ]

crates = np.array([(agent_pos[0], agent_pos[1] - 1),
          (agent_pos[0], agent_pos[1] + 1),
          (agent_pos[0] - 1, agent_pos[1]),])

field[tuple(crates.T)] = 1

print("UP", "RIGHT", "DOWN", "LEFT", "WAIT")
print("Field feature", get_field_feature(agent_pos, field, explosion_map, bombs) - 1)
print("Safety feature", get_safety_feature(agent_pos, field, explosion_map, bombs))

field[agent_pos] = 2
bomb_coords = bombs[0][0]#[bomb[0] for bomb in bombs]
for bomb in bombs:
  b = bomb[0]
  field[b] = 6
my_x, my_y = agent_pos[0], agent_pos[1]
field[0,1] = 1
print(field.T)


176
UP RIGHT DOWN LEFT WAIT
Field feature tensor([1, 3, 1, 1, 0])
Safety feature tensor([0, 0, 0, 0, 0])
[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  1 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  1  2  6  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  1 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1

171


In [8]:
import torch
table_path = "model/my-model.pt"
table = torch.load(table_path)
print(f"Table shape {table.shape}")
print(f"Number of elements {table.numel()}")
print(f"RAM {table.numel() * table.element_size() / (2**20)} MB")

Table shape torch.Size([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6])
Number of elements 98304
RAM 0.75 MB


In [20]:
import torch
table_stat_path = "model/my-model_stats.pt"
table_stats = torch.load(table_stat_path)
print(f"Explored state ratio: {torch.sum(table_stats > 0) / table_stats.numel():.2%}")

Explored state ratio: 0.84%
